---
title: "Final Projects"
description: "A list of final projects for PSYC 3043"
author: "Abhilasha Kumar"
date-modified: last-modified
order: 15
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page describes the details for your final project. Your final project is worth 40% of your final grade and is an individual project. You have the option to choose from three different options (see below).

## Project options

### Minute Intelligence

For this project, you will create a 3 to 5 minute video on any instance of cognition that we did not cover but interests you. Your video should introduce the topic, examine its relevance to real life, and then describe the research that has been conducted on the topic so far in an engaging and educational manner. Details about different milestones for this project are available [here](https://docs.google.com/document/d/1WiAL1RBFt6OLRx-43awGxZacst2UJXYZ/edit?usp=share_link&ouid=114230382498081849934&rtpof=true&sd=true).

### Gamifying Intelligence

For this project, you will create a game that tests an instance of cognition and present a jointly designed poster. The game can be single or multi-player, but you will need to specify (1) your target research question, (2) independent variable(s), (3) dependent variables, and (4) expected patterns of behavior and how they correspond to the instance of cognition you are attempting to study. The game should be playable in person (via index cards, etc.) or online (via a survey). Details about different milestones for this project are available [here](https://docs.google.com/document/d/1rC8gnxmMbp9vuKWeEDv0rLzBRRlTAqnd/edit?usp=sharing&ouid=114230382498081849934&rtpof=true&sd=true).

### Intelligence Review 

For this project, you will write an APA-style review paper on a specific aspect of intelligence that we have NOT covered in class.

## Milestones 

There will be several formative low-stakes milestones during the semester to ensure you are making steady progress towards the final project. Due dates for these milestones are available on Canvas. The breakdown of how the milestones contribute to your final project grade is below:

| Milestone | Points       |
|:-------------|:------------|
| Project selection            | 5    |
| Selection of aspect of intelligence           | 5  |
| QALMRI for research articles           | 10 |
| Project plan/outline            | 5 |
| First draft           | 2.5    |
| Final submission           | 12.5 |
| **Total**           | 40 |

### Milestone 1: Project selection (5 points)

This assessment will happen relatively early in the semester to ensure that you are clear on the different demands of the project options. This assessment will be graded for thoughtful effort, i.e., I want to see that you have made an effort to select the option that best aligns with your goals for this class. 

### Milestone 2: Selection of aspect of intelligence (5 points)

This assessment will help you think about the particular instance of cognition that you might want to explore. Note that the aspect of intelligence you select will depend on the project you have selected, so this assessment may also involve describing some specifics of your project. This assessment will be graded for thoughtful effort, i.e., I want to see that you have made an effort to identify an instance of cognition that aligns well with the project you have selected. 

### Milestone 3: QALMRI for research articles (10 points)

This assessment will help you organize your literature review and structure your analysis and/or writing/designing. You will prepare a list of 1 review and 5 primary/empirical research articles relevant to your project and submit SPARK/QALMRI reports for each of the articles. This will help you understand the research articles in detail and enable you to ultimately connect ideas across readings.

### Milestone 4: Project plan/outline (5 points)

This assessment is intended to help you organize your overall plan for the final project. The specifics of the plan/outline will vary based on your chosen project, but you will be required to submit a rough outline/plan. This assessment will be graded for thoughtful effort, i.e., I want to see that you are making steady progress on your project and are able to integrate the research articles you have read with key arguments/analyses. 

### Milestone 5: First draft (2.5 points)

This assessment is intended to provide you feedback on your nearly-final submission. The goal is to make sure you are on track to submitting a strong final project. This assessment will be graded for thoughtful effort, i.e., I want to see that you are making steady progress on your project.

### Milestone 6: Final submission (12.5 points)

This final assessment will require you to submit your final project and all its components. The specifics of your submission will vary based on your chosen project, so please refer to the details of your project to make sure you submit all required materials.

