---
title: "Reading List"
---

### Week 1: Getting Started

#### Thursday, August 31, 2023

- Syllabus
- Empirical paper QALMRI
- Review paper / Podcast: SPARK

### Week 2: Intelligence 101

#### Tuesday, September 5, 2023

- Yakushko, O. (2019). Eugenics and its evolution in the history of western psychology: A critical archival review. <i>Psychotherapy and Politics International, 17</i>(2), e1495.
- Coane, J. H., Cipollini, J., Barrett, T. E., Kavaler, J., & Umanath, S. (2023). Lay Definitions of Intelligence, Knowledge, and Memory: Inter-and Independence of Constructs. <i>Journal of Intelligence, 11</i>(5), 84.


#### Thursday, September 7, 2023

- Griffiths, T. L. (2020). Understanding human intelligence through human limitations. <i> Trends in Cognitive Sciences</i>, 24(11), 873-883.


### Week 3: Statistical Learning

#### Tuesday, September 12, 2023

- Saffran, J. R., Aslin, R. N., & Newport, E. L. (1996). Statistical learning by 8-month-old infants. <i>Science, 274</i>(5294), 1926-1928.
- Saffran, J. R., & Kirkham, N. Z. (2018). Infant statistical learning. <i>Annual Review of Psychology, 69</i>, 181-203.

### Thursday, September 14, 2023

- Unger, L., Vales, C., & Fisher, A. V. (2020). The role of co‐occurrence statistics in developing semantic knowledge. <i>Cognitive Science, 44</i>(9), e12894.

### Week 4: Statistical Learning & Other Minds

#### Tuesday, September 19, 2023

- Hauser, M. D., Newport, E. L., & Aslin, R. N. (2001). Segmentation of the speech stream in a non-human primate: Statistical learning in cotton-top tamarins. Cognition, 78(3), B53-B64.
- Santolin, C., & Saffran, J. R. (2018). Constraints on statistical learning across species. Trends in Cognitive Sciences, 22(1), 52-63.

#### Thursday, September 21, 2023

- Frost, R., Armstrong, B. C., & Christiansen, M. H. (2019). Statistical learning research: A critical review and possible new directions. Psychological Bulletin, 145(12), 1128.

### Week 5: Modeling Language

#### Tuesday, September 26, 2023

- Lake, B. M., & Murphy, G. L. (2021). Word meaning in minds and machines. Psychological review.

#### Thursday, September 28, 2023

- Cassenti, D. N., Veksler, V. D., & Ritter, F. E. (2022). Editor's Review and Introduction: Cognition‐Inspired Artificial Intelligence. Topics in Cognitive Science, 14(4), 652-664.
- - DeepMind Podcast: <a href="https://www.youtube.com/watch?v=21JSKHR7KWw">Speaking of intelligence</a><strong>(38 mins)</strong>

### Week 6: Biases and Origins

#### Tuesday, October 3, 2023

- Bender, E. M., Gebru, T., McMillan-Major, A., & Shmitchell, S. (2021, March). On the dangers of stochastic parrots: Can language models be too big?🦜. In Proceedings of the 2021 ACM conference on fairness, accountability, and transparency (pp. 610-623).
- Many Minds Podcast: <a href="https://manyminds.libsyn.com/what-is-language-for">What is language for?</a> <strong>(1 h 17 mins)</strong>

#### Thursday, October 5, 2023

- Project Discussion 

### Week 7: Perceptual Learning

#### Tuesday, October 10, 2023

- FALL BREAK! No class!

#### Thursday, October 12, 2023

- Fiser, J., & Aslin, R. N. (2002). Statistical learning of new visual feature combinations by infants. Proceedings of the National Academy of Sciences, 99(24), 15822-15826.
- Smith, L. B., Jayaraman, S., Clerkin, E., & Yu, C. (2018). The developing infant creates a curriculum for statistical learning. Trends in cognitive sciences, 22(4), 325-336.

### Week 8: Language and grounding

#### Tuesday, October 17, 2023

- Glenberg, A. M., & Kaschak, M. P. (2002). Grounding language in action. Psychonomic bulletin & review, 9(3), 558-565.
- Morey, R. D., Kaschak, M. P., Díez-Álamo, A. M., Glenberg, A. M., Zwaan, R. A., Lakens, D., ... & Ziv-Crispel, N. (2022). A pre-registered, multi-lab non-replication of the action-sentence compatibility effect (ACE). Psychonomic bulletin & review, 29(2), 613-626.

#### Thursday, October 19, 2023



### Week 9: Modeling Perception

### Week 10: Theory of Mind

### Week 11: Animal and Machine Theory of Mind

### Week 12: Consciousness

### Week 13: Complex Cognition

### Week 14: Cumulative Culture

### Week 15: Human Uniqueness

